const state={profile:null,dashboard:null,activeTab:"overview",chartRange:30};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const el={telegramUserId:$("#telegramUserId"),loadDashboard:$("#loadDashboard"),logoutButton:$("#logoutButton"),seedDemoButton:$("#seedDemoButton"),dashboard:$("#dashboard"),summaryGrid:$("#summaryGrid"),profileHeadline:$("#profileHeadline"),profileSubline:$("#profileSubline"),profileBlock:$("#profileBlock"),todayBlock:$("#todayBlock"),macroBars:$("#macroBars"),progressBlock:$("#progressBlock"),progressTimeline:$("#progressTimeline"),progressSpotlight:$("#progressSpotlight"),periodCompare:$("#periodCompare"),historyBlock:$("#historyBlock"),weightBlock:$("#weightBlock"),measurementBlock:$("#measurementBlock"),answerBlock:$("#answerBlock"),mealPlanBlock:$("#mealPlanBlock"),weightChart:$("#weightChart"),measurementChart:$("#measurementChart"),weightChartRangeLabel:$("#weightChartRangeLabel"),progressRangeLabel:$("#progressRangeLabel"),miniWeightValue:$("#miniWeightValue"),miniWeightDelta:$("#miniWeightDelta"),miniWeightChart:$("#miniWeightChart"),miniCaloriesValue:$("#miniCaloriesValue"),miniCaloriesCaption:$("#miniCaloriesCaption"),miniCaloriesChart:$("#miniCaloriesChart"),miniWaistValue:$("#miniWaistValue"),miniWaistDelta:$("#miniWaistDelta"),miniMeasurementChart:$("#miniMeasurementChart"),weightForm:$("#weightForm"),measurementForm:$("#measurementForm"),mealForm:$("#mealForm"),askForm:$("#askForm"),loadMealPlan:$("#loadMealPlan"),weightValue:$("#weightValue"),waistValue:$("#waistValue"),thighValue:$("#thighValue"),armValue:$("#armValue"),mealDescription:$("#mealDescription"),mealType:$("#mealType"),questionValue:$("#questionValue"),statusLine:$("#statusLine"),telegramLoginWidget:$("#telegramLoginWidget"),tabButtons:$$(".tab-button"),tabPanels:$$(".tab-panel"),rangeButtons:$$(".range-button")};

const fmtDate=v=>v?new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit"}).format(new Date(v)):"без даты";
const fmtDateLong=v=>v?new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(v)):"без даты";
const fmtDateTime=v=>v?new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"без даты";
const fmtNum=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):"0";
const fmtSigned=(v,s="")=>Number.isFinite(Number(v))?`${Number(v)>0?"+":""}${Number(v).toFixed(1)}${s}`:"—";
const rangeLabel=d=>d===7?"За неделю":"За месяц";

function iconSvg(kind){const map={profile:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z"></path><path d="M4 20a8 8 0 0 1 16 0"></path></svg>',today:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3v18"></path><path d="M3 12h18"></path></svg>',weight:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 5v5"></path><path d="M6.2 7.2 12 10"></path><path d="M5 14a7 7 0 1 0 14 0 7 7 0 0 0-14 0Z"></path></svg>',trend:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m4 16 5-5 4 4 7-8"></path><path d="M20 7v5h-5"></path></svg>',measure:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 7h16"></path><path d="M7 7v10"></path><path d="M12 7v10"></path><path d="M17 7v10"></path><path d="M4 17h16"></path></svg>',calories:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3c2 3 5 5.5 5 9a5 5 0 1 1-10 0c0-2.8 1.7-4.9 5-9Z"></path></svg>',protein:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6 7c0-2 1.5-3 3-3h6c1.5 0 3 1 3 3s-1 3-3 3H9c-2 0-3 1-3 3s1.5 3 3 3h6c1.5 0 3 1 3 3"></path></svg>'};return map[kind]||map.trend;}
function iconFor(label){const l=String(label).toLowerCase();if(l.includes("проф"))return"profile";if(l.includes("сегодня")||l.includes("кбжу"))return"today";if(l.includes("вес"))return"weight";if(l.includes("динам"))return"trend";if(l.includes("замер")||l.includes("талия")||l.includes("нога")||l.includes("рука"))return"measure";if(l.includes("калор"))return"calories";if(l.includes("бел"))return"protein";return"trend";}
function metric(label,value){const x=document.createElement("div");x.className="metric";const icon=iconFor(label);x.innerHTML=`<span class="metric-icon">${iconSvg(icon)}</span><strong>${label}</strong><div>${value}</div>`;return x;}
function listItem(title,subtitle=""){const x=document.createElement("div");x.className="list-item";x.innerHTML=subtitle?`<strong>${title}</strong><div class="status">${subtitle}</div>`:`<strong>${title}</strong>`;return x;}
function summaryCard(label,value,caption=""){const x=document.createElement("article");x.className="summary-card";const icon=iconFor(label);x.innerHTML=`<span class="summary-icon">${iconSvg(icon)}</span><span class="summary-label">${label}</span><div class="summary-value">${value}</div><div class="summary-caption">${caption}</div>`;return x;}
function fill(node,items){node.innerHTML="";(items.length?items:[listItem("Пока пусто")]).forEach(i=>node.append(i));}

async function request(pathname,options={}){const response=await fetch(pathname,{credentials:"include",headers:{"Content-Type":"application/json"},...options});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Не удалось выполнить запрос");return payload;}
function setStatus(text,tone="muted"){el.statusLine.textContent=text;el.statusLine.dataset.tone=tone;}
function setAuthUi(ok){el.logoutButton.classList.toggle("hidden",!ok);el.seedDemoButton.classList.toggle("hidden",!ok);}
function setActiveTab(name){state.activeTab=name;el.tabButtons.forEach(b=>b.classList.toggle("active",b.dataset.tab===name));el.tabPanels.forEach(p=>p.classList.toggle("active",p.dataset.panel===name));}
function setChartRange(days){state.chartRange=days;el.rangeButtons.forEach(b=>b.classList.toggle("active",Number(b.dataset.range)===days));renderDashboardSections();}
function filterLogs(logs=[],days=30){if(!logs.length)return[];const cutoff=new Date();cutoff.setHours(0,0,0,0);cutoff.setDate(cutoff.getDate()-(days-1));const filtered=logs.filter(log=>new Date(log.created_at)>=cutoff);return filtered.length?filtered:logs.slice(0,Math.min(days,logs.length));}

function coords(points,w,h,min,max,accessor){return points.map((point,index)=>{const x=points.length===1?w/2:index/(points.length-1)*w;const raw=accessor(point);const norm=max===min?0.5:(raw-min)/(max-min);return{x,y:h-norm*h,point};});}
function linePath(points){return points.map((p,i)=>`${i===0?"M":"L"} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(" ");}
function areaPath(points,h){if(!points.length)return"";const first=points[0],last=points[points.length-1];return`${linePath(points)} L ${last.x.toFixed(2)} ${h} L ${first.x.toFixed(2)} ${h} Z`;}
function emptyChart(node,msg){node.innerHTML=`<div class="chart-empty">${msg}</div>`;}

function spark(node,values,color){const points=values.filter(v=>Number.isFinite(v));if(!points.length){node.innerHTML='<div class="sparkline-empty"></div>';return;}const w=220,h=76,min=Math.min(...points),max=Math.max(...points);const c=coords(points,w,h,min,max,p=>p),line=linePath(c),area=areaPath(c,h),gid=`s${Math.random().toString(36).slice(2,8)}`;node.innerHTML=`<svg class="sparkline-svg" viewBox="0 0 ${w} ${h}" aria-hidden="true"><defs><linearGradient id="${gid}" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="${color}" stop-opacity="0.34"></stop><stop offset="100%" stop-color="${color}" stop-opacity="0"></stop></linearGradient></defs><path d="${area}" fill="url(#${gid})"></path><path d="${line}" fill="none" stroke="${color}" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>`;}

function lineChart(node,logs,{title,accessor,color,suffix,precision=1,rangeText,emptyMessage}){if(!logs?.length)return emptyChart(node,emptyMessage);const points=[...logs].reverse();const values=points.map(accessor).filter(v=>Number.isFinite(v));if(!values.length)return emptyChart(node,emptyMessage);const w=760,h=240,min=Math.min(...values),max=Math.max(...values),c=coords(points,w,h,min,max,accessor),line=linePath(c),area=areaPath(c,h),gid=`l${Math.random().toString(36).slice(2,8)}`;const grid=[0,0.25,0.5,0.75,1].map(r=>`<line x1="0" y1="${(h*r).toFixed(2)}" x2="${w}" y2="${(h*r).toFixed(2)}" stroke="rgba(255,255,255,0.07)" stroke-width="1" />`).join("");node.innerHTML=`<div class="chart-meta"><span>${rangeText} · диапазон ${fmtNum(min,precision)}–${fmtNum(max,precision)} ${suffix}</span><span>${fmtDateLong(points[0].created_at)} — ${fmtDateLong(points[points.length-1].created_at)}</span></div><svg class="chart-svg" viewBox="0 0 ${w} ${h+34}" role="img" aria-label="${title}"><defs><linearGradient id="${gid}" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="${color}" stop-opacity="0.34"></stop><stop offset="100%" stop-color="${color}" stop-opacity="0"></stop></linearGradient></defs>${grid}<path d="${area}" fill="url(#${gid})"></path><path d="${line}" fill="none" stroke="${color}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"></path>${c.map(p=>`<circle cx="${p.x.toFixed(2)}" cy="${p.y.toFixed(2)}" r="4.5" fill="${color}" />`).join("")}${c.map(p=>`<text x="${p.x.toFixed(2)}" y="${h+24}" text-anchor="middle" font-size="12" fill="rgba(156,175,192,0.86)">${fmtDate(p.point.created_at)}</text>`).join("")}</svg>`;}

function multiLineChart(node,logs,rangeText){if(!logs?.length)return emptyChart(node,"Добавь замеры или подгрузи демо-данные, чтобы увидеть график.");const points=[...logs].reverse().map(log=>({...log,waist:Number(log.waist),thigh:Number(log.thigh),arm:Number(log.arm)})).filter(log=>[log.waist,log.thigh,log.arm].some(v=>Number.isFinite(v)));if(!points.length)return emptyChart(node,"Замеров пока недостаточно для графика.");const w=760,h=240,all=points.flatMap(p=>[p.waist,p.thigh,p.arm]).filter(v=>Number.isFinite(v)),min=Math.min(...all),max=Math.max(...all),series=[["waist","#25d0a5"],["thigh","#f0bc66"],["arm","#56b6ff"]];const grid=[0,0.25,0.5,0.75,1].map(r=>`<line x1="0" y1="${(h*r).toFixed(2)}" x2="${w}" y2="${(h*r).toFixed(2)}" stroke="rgba(255,255,255,0.07)" stroke-width="1" />`).join("");const paths=series.map(([key,color])=>{if(!points.some(p=>Number.isFinite(p[key])))return"";const c=coords(points,w,h,min,max,p=>Number.isFinite(Number(p[key]))?Number(p[key]):min);return`<path d="${linePath(c)}" fill="none" stroke="${color}" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round"></path>`;}).join("");node.innerHTML=`<div class="chart-meta"><span>${rangeText} · диапазон ${fmtNum(min)}–${fmtNum(max)} см</span><span>${fmtDateLong(points[0].created_at)} — ${fmtDateLong(points[points.length-1].created_at)}</span></div><svg class="chart-svg" viewBox="0 0 ${w} ${h+34}" role="img" aria-label="График замеров">${grid}${paths}${points.map((p,i)=>{const x=points.length===1?w/2:i/(points.length-1)*w;return`<text x="${x.toFixed(2)}" y="${h+24}" text-anchor="middle" font-size="12" fill="rgba(156,175,192,0.86)">${fmtDate(p.created_at)}</text>`;}).join("")}</svg>`;}

function renderMacroBars(profile,today){const t=today?.totals||{},items=[["Калории",Number(t.calories||0),Number(profile.daily_calories||0),"ккал","calories"],["Белки",Number(t.protein||0),Number(profile.daily_protein||0),"г","protein"],["Жиры",Number(t.fat||0),Number(profile.daily_fat||0),"г","fat"],["Углеводы",Number(t.carbs||0),Number(profile.daily_carbs||0),"г","carbs"]];el.macroBars.innerHTML=items.map(([label,value,goal,unit,className])=>{const ratio=goal>0?Math.min(100,value/goal*100):0;return`<div class="macro-row"><div class="macro-top"><span>${label}</span><strong>${fmtNum(value)} / ${goal||0} ${unit}</strong></div><div class="macro-track"><div class="macro-fill ${className}" style="width:${ratio}%"></div></div></div>`;}).join("");}

function renderSummary(d){const p=d.profile,meals=d.today?.meals||[],totals=d.today?.totals||{},weight=d.weightLogs?.logs?.[0],measure=d.measurementLogs?.logs?.[0];el.profileHeadline.textContent=p.display_name||"Твой кабинет";el.profileSubline.textContent=p.telegram_username?`@${p.telegram_username} · цель: ${p.goal||"не указана"}`:`цель: ${p.goal||"не указана"}`;el.summaryGrid.innerHTML="";[summaryCard("Сегодня",`${Math.round(Number(totals.calories||0))} ккал`,`${meals.length} приемов пищи`),summaryCard("Текущий вес",weight?`${fmtNum(weight.weight)} кг`:"—",weight?fmtDateLong(weight.created_at):"нет записей"),summaryCard("Динамика веса",d.weightProgress?.change!==undefined?fmtSigned(d.weightProgress.change," кг"):"—",d.weightProgress?.change>0?"рост":d.weightProgress?.change<0?"снижение":"без изменений"),summaryCard("Последние замеры",measure?`${measure.waist??"-"} / ${measure.thigh??"-"} / ${measure.arm??"-"}`:"—",measure?"талия / нога / рука":"нет записей")].forEach(card=>el.summaryGrid.append(card));}

function renderHeroCards(d,weightLogs,measurementLogs){const totals=d.today?.totals||{},meals=d.recentMeals?.meals||[],latestWeight=d.weightLogs?.logs?.[0],latestMeasurement=d.measurementLogs?.logs?.[0],earliestWeight=weightLogs[weightLogs.length-1],earliestMeasurement=measurementLogs[measurementLogs.length-1];const weightDelta=latestWeight&&earliestWeight?Number(latestWeight.weight)-Number(earliestWeight.weight):Number.NaN;const waistDelta=latestMeasurement&&earliestMeasurement&&latestMeasurement.waist!==null&&earliestMeasurement.waist!==null?Number(latestMeasurement.waist)-Number(earliestMeasurement.waist):Number.NaN;el.miniWeightValue.textContent=latestWeight?`${fmtNum(latestWeight.weight)} кг`:"—";el.miniWeightDelta.textContent=Number.isFinite(weightDelta)?fmtSigned(weightDelta," кг"):"нет данных";el.miniCaloriesValue.textContent=`${Math.round(Number(totals.calories||0))} ккал`;el.miniCaloriesCaption.textContent=meals.length?`${meals.length} приемов пищи`:"сегодня";el.miniWaistValue.textContent=latestMeasurement?.waist?`${fmtNum(latestMeasurement.waist)} см`:"—";el.miniWaistDelta.textContent=Number.isFinite(waistDelta)?fmtSigned(waistDelta," см"):"нет данных";spark(el.miniWeightChart,[...weightLogs].reverse().map(log=>Number(log.weight)),"#25d0a5");spark(el.miniCaloriesChart,[...meals].reverse().slice(-8).map(meal=>Number(meal.calories)),"#f0bc66");spark(el.miniMeasurementChart,[...measurementLogs].reverse().map(log=>Number(log.waist)),"#56b6ff");}

function renderProfile(profile){fill(el.profileBlock,[metric("Профиль",profile.display_name||"Не настроен"),metric("Telegram",profile.telegram_username?`@${profile.telegram_username}`:profile.telegram_user_id),metric("Цель",profile.goal||"Не указана"),metric("Калории",`${profile.daily_calories||0} ккал`),metric("Белки",`${profile.daily_protein||0} г`),metric("Жиры / углеводы",`${profile.daily_fat||0} / ${profile.daily_carbs||0} г`)]);}
function renderToday(today){const meals=today?.meals||[],totals=today?.totals||{},items=[metric("Калории",`${Math.round(Number(totals.calories||0))} ккал`),metric("БЖУ",`${fmtNum(totals.protein||0)} / ${fmtNum(totals.fat||0)} / ${fmtNum(totals.carbs||0)} г`)];if(meals.length){meals.slice(0,6).forEach(meal=>items.push(listItem(`${meal.meal_type||"Прием пищи"} · ${meal.dish_name}`,`${Math.round(Number(meal.calories||0))} ккал · ${fmtDateTime(meal.created_at)}`)));}else items.push(listItem("Сегодня пока нет приемов пищи"));fill(el.todayBlock,items);}

function renderProgress(weightLogs,measurementLogs){const latestWeight=weightLogs[0],earliestWeight=weightLogs[weightLogs.length-1],latestMeasurement=measurementLogs[0],earliestMeasurement=measurementLogs[measurementLogs.length-1],items=[];if(latestWeight&&earliestWeight){items.push(metric("Вес",`${fmtNum(earliestWeight.weight)} → ${fmtNum(latestWeight.weight)} кг`));items.push(metric("Изменение веса",fmtSigned(Number(latestWeight.weight)-Number(earliestWeight.weight)," кг")));}else items.push(metric("Вес","Недостаточно данных"));if(latestMeasurement&&earliestMeasurement){const waist=latestMeasurement.waist!==null&&earliestMeasurement.waist!==null?Number(latestMeasurement.waist)-Number(earliestMeasurement.waist):null;const thigh=latestMeasurement.thigh!==null&&earliestMeasurement.thigh!==null?Number(latestMeasurement.thigh)-Number(earliestMeasurement.thigh):null;const arm=latestMeasurement.arm!==null&&earliestMeasurement.arm!==null?Number(latestMeasurement.arm)-Number(earliestMeasurement.arm):null;items.push(metric("Талия",waist===null?"нет данных":fmtSigned(waist," см")));items.push(metric("Нога",thigh===null?"нет данных":fmtSigned(thigh," см")));items.push(metric("Рука",arm===null?"нет данных":fmtSigned(arm," см")));}else items.push(metric("Замеры","Пока нет динамики"));fill(el.progressBlock,items);}

function compareDelta(logs,key,days){const filtered=filterLogs(logs,days);const latest=filtered[0],earliest=filtered[filtered.length-1];if(!latest||!earliest)return null;const lv=Number(latest[key]),ev=Number(earliest[key]);if(!Number.isFinite(lv)||!Number.isFinite(ev))return null;return lv-ev;}
function renderProgressPremium(weightLogs,measurementLogs){const weekWeight=compareDelta(weightLogs,"weight",7);const monthWeight=compareDelta(weightLogs,"weight",30);const weekWaist=compareDelta(measurementLogs,"waist",7);const monthWaist=compareDelta(measurementLogs,"waist",30);const latestWeight=weightLogs[0];const latestMeasurement=measurementLogs[0];el.progressSpotlight.innerHTML=`<article class="spotlight-card"><span class="spotlight-label">Прогресс тела</span><div class="spotlight-value">${latestWeight?fmtNum(latestWeight.weight)+" кг":"—"}</div><div class="spotlight-caption">Текущий вес и живая динамика по выбранному периоду. Последняя запись${latestWeight?` от ${fmtDateLong(latestWeight.created_at)}`:" пока отсутствует"}.</div></article><article class="spotlight-card"><span class="spotlight-label">Ключевой замер</span><div class="spotlight-value">${latestMeasurement?.waist?fmtNum(latestMeasurement.waist)+" см":"—"}</div><div class="spotlight-caption">Фокус на талии как главном индикаторе композиции тела. ${Number.isFinite(monthWaist)?`За месяц ${fmtSigned(monthWaist," см")}.`:"Пока мало данных для сравнения."}</div></article>`;el.periodCompare.innerHTML=[{label:"Вес · 7 дней",value:weekWeight,suffix:" кг",meta:"Сравнение внутри короткого периода"},{label:"Вес · 30 дней",value:monthWeight,suffix:" кг",meta:"Показывает общую месячную тенденцию"},{label:"Талия · 30 дней",value:monthWaist,suffix:" см",meta:Number.isFinite(weekWaist)?`За 7 дней ${fmtSigned(weekWaist," см")}`:"Недельных данных пока мало"}].map(item=>`<article class="compare-card"><span class="compare-label">${item.label}</span><div class="compare-value">${Number.isFinite(item.value)?fmtSigned(item.value,item.suffix):"—"}</div><div class="compare-caption">${item.meta}</div></article>`).join("");}

function renderTimeline(weightLogs,measurementLogs){const items=[];weightLogs.forEach(log=>items.push({date:log.created_at,title:`Вес обновлен: ${fmtNum(log.weight)} кг`,subtitle:fmtDateLong(log.created_at)}));measurementLogs.forEach(log=>items.push({date:log.created_at,title:`Замеры: талия ${log.waist??"-"} · нога ${log.thigh??"-"} · рука ${log.arm??"-"}`,subtitle:fmtDateLong(log.created_at)}));items.sort((a,b)=>new Date(b.date)-new Date(a.date));el.progressTimeline.innerHTML=items.length?items.slice(0,12).map(item=>`<article class="timeline-item"><div class="timeline-dot"></div><div class="timeline-body"><strong>${item.title}</strong><div class="status">${item.subtitle}</div></div></article>`).join(""):'<div class="chart-empty">История прогресса появится после первых записей.</div>';}

function renderHistory(meals){fill(el.historyBlock,meals.length?meals.map(meal=>listItem(`${fmtDateLong(meal.created_at)} — ${meal.dish_name}`,`${meal.meal_type||"Прием пищи"} · ${Math.round(Number(meal.calories||0))} ккал · БЖУ ${fmtNum(meal.protein)} / ${fmtNum(meal.fat)} / ${fmtNum(meal.carbs)}`)):[listItem("История питания пока пустая")]);}
function renderWeightLogs(logs){fill(el.weightBlock,logs.length?logs.slice(0,12).map(log=>listItem(`${fmtDateLong(log.created_at)} — ${fmtNum(log.weight)} кг`)):[listItem("Журнал веса пока пуст")]);}
function renderMeasurementLogs(logs){fill(el.measurementBlock,logs.length?logs.slice(0,12).map(log=>listItem(`${fmtDateLong(log.created_at)} — талия ${log.waist??"-"} · нога ${log.thigh??"-"} · рука ${log.arm??"-"}`,log.note||"")):[listItem("Журнал замеров пока пуст")]);}

function renderDashboardSections(){if(!state.dashboard)return;const d=state.dashboard,weightLogs=d.weightLogs?.logs||[],measurementLogs=d.measurementLogs?.logs||[],recentMeals=d.recentMeals?.meals||[],filteredWeight=filterLogs(weightLogs,state.chartRange),filteredMeasurements=filterLogs(measurementLogs,state.chartRange),text=rangeLabel(state.chartRange);el.dashboard.classList.remove("hidden");setAuthUi(true);el.weightChartRangeLabel.textContent=text;el.progressRangeLabel.textContent=text;renderHeroCards(d,filteredWeight,filteredMeasurements);renderSummary(d);renderProfile(d.profile);renderToday(d.today);renderMacroBars(d.profile,d.today);renderProgressPremium(weightLogs,measurementLogs);renderProgress(filteredWeight,filteredMeasurements);renderTimeline(filteredWeight,filteredMeasurements);renderHistory(recentMeals);renderWeightLogs(weightLogs);renderMeasurementLogs(measurementLogs);lineChart(el.weightChart,filteredWeight,{title:"График веса",accessor:p=>Number(p.weight),color:"#25d0a5",suffix:"кг",precision:1,rangeText:text,emptyMessage:"Добавь несколько записей веса или подгрузи демо-данные, чтобы увидеть график."});multiLineChart(el.measurementChart,filteredMeasurements,text);}
function renderDashboard(d){state.profile=d.profile;state.dashboard=d;renderDashboardSections();}

async function loadDashboardBySession(){setStatus("Загружаю кабинет...","muted");renderDashboard(await request("/api/dashboard"));setStatus("Кабинет открыт.","success");}
async function loadDashboardByFallback(){const identifier=el.telegramUserId.value.trim();if(!identifier)return setStatus("Введи Telegram ID или @username, чтобы открыть кабинет.","error");setStatus("Загружаю кабинет...","muted");renderDashboard(await request(`/api/dashboard?identifier=${encodeURIComponent(identifier)}`));setStatus("Кабинет открыт.","success");}
async function submitWeight(event){event.preventDefault();const weight=el.weightValue.value.trim();if(!weight)return setStatus("Введи вес, чтобы сохранить запись.","error");try{await request("/api/weight",{method:"POST",body:JSON.stringify({weight})});el.weightForm.reset();await loadDashboardBySession();setStatus("Вес сохранен.","success");}catch(error){setStatus(error.message,"error");}}
async function submitMeasurements(event){event.preventDefault();try{await request("/api/measurements",{method:"POST",body:JSON.stringify({waist:el.waistValue.value||null,thigh:el.thighValue.value||null,arm:el.armValue.value||null})});el.measurementForm.reset();await loadDashboardBySession();setStatus("Замеры сохранены.","success");}catch(error){setStatus(error.message,"error");}}
async function submitMeal(event){event.preventDefault();const description=el.mealDescription.value.trim();if(!description)return setStatus("Опиши еду, чтобы добавить прием пищи.","error");try{await request("/api/meal",{method:"POST",body:JSON.stringify({description,meal_type:el.mealType.value||"не указано"})});el.mealForm.reset();await loadDashboardBySession();setActiveTab("nutrition");setStatus("Прием пищи добавлен в дневник.","success");}catch(error){setStatus(error.message,"error");}}
async function submitQuestion(event){event.preventDefault();const question=el.questionValue.value.trim();if(!question)return setStatus("Напиши вопрос, чтобы получить ответ.","error");try{const result=await request("/api/ask",{method:"POST",body:JSON.stringify({question})});fill(el.answerBlock,[listItem("Ответ нутрициолога",result.answer)]);setStatus("Ответ готов.","success");}catch(error){setStatus(error.message,"error");}}
async function loadMealPlan(){try{const result=await request("/api/meal-plan",{method:"POST",body:JSON.stringify({period:"день"})});fill(el.mealPlanBlock,[listItem("Меню на день",result.plan)]);setStatus("Меню на день готово.","success");}catch(error){setStatus(error.message,"error");}}
async function seedDemoData(){try{setStatus("Добавляю демо-историю для графиков...","muted");const result=await request("/api/demo/seed",{method:"POST",body:JSON.stringify({})});await loadDashboardBySession();setStatus(`Готово: вес ${result.seededWeights}, замеры ${result.seededMeasurements}, питание ${result.seededMeals}.`,"success");}catch(error){setStatus(error.message,"error");}}
async function logout(){await request("/api/logout",{method:"POST",body:JSON.stringify({})});state.profile=null;state.dashboard=null;el.dashboard.classList.add("hidden");setAuthUi(false);setStatus("Ты вышел из кабинета.","success");}

async function bootstrapTelegramLogin(){try{const config=await request("/api/web-config");if(!config.botUsername)throw new Error("Не удалось определить username бота для Telegram Login.");const script=document.createElement("script");script.async=true;script.src="https://telegram.org/js/telegram-widget.js?22";script.setAttribute("data-telegram-login",config.botUsername);script.setAttribute("data-size","large");script.setAttribute("data-userpic","false");script.setAttribute("data-request-access","write");script.setAttribute("data-auth-url",config.authUrl||"/auth/telegram/callback");el.telegramLoginWidget.innerHTML="";el.telegramLoginWidget.append(script);setStatus("Вход через Telegram готов.","muted");}catch(error){setStatus(error.message,"error");}}
function consumeAuthResultFlags(){const url=new URL(window.location.href),authSuccess=url.searchParams.get("auth_success"),authError=url.searchParams.get("auth_error");if(!authSuccess&&!authError)return{authSuccess:false,authError:null};url.searchParams.delete("auth_success");url.searchParams.delete("auth_error");window.history.replaceState({},document.title,url.pathname+url.search+url.hash);return{authSuccess:authSuccess==="1",authError};}
async function restoreSession(){try{await request("/api/me");await loadDashboardBySession();}catch{setAuthUi(false);}}

el.loadDashboard.addEventListener("click",()=>loadDashboardByFallback().catch(error=>setStatus(error.message,"error")));
el.logoutButton.addEventListener("click",()=>logout().catch(error=>setStatus(error.message,"error")));
el.seedDemoButton.addEventListener("click",()=>seedDemoData().catch(error=>setStatus(error.message,"error")));
el.weightForm.addEventListener("submit",submitWeight);
el.measurementForm.addEventListener("submit",submitMeasurements);
el.mealForm.addEventListener("submit",submitMeal);
el.askForm.addEventListener("submit",submitQuestion);
el.loadMealPlan.addEventListener("click",loadMealPlan);
el.telegramUserId.addEventListener("keydown",event=>{if(event.key==="Enter"){event.preventDefault();loadDashboardByFallback().catch(error=>setStatus(error.message,"error"));}});
el.tabButtons.forEach(button=>button.addEventListener("click",()=>setActiveTab(button.dataset.tab)));
el.rangeButtons.forEach(button=>button.addEventListener("click",()=>setChartRange(Number(button.dataset.range))));

bootstrapTelegramLogin();
const authFlags=consumeAuthResultFlags();
restoreSession().then(()=>{if(authFlags.authError)setStatus("Не удалось подтвердить вход через Telegram.","error");else if(authFlags.authSuccess)setStatus("Вход через Telegram выполнен.","success");});
